streams_directory:  "./config/streams/cams_era5/"
start_date: 200301010000

ae_local_num_blocks: 0
ae_global_num_blocks: 4
ae_global_trailing_layer_norm: false
forecast_offset: 1
forecast_steps: 4
forecast_policy: fixed
forecast_freeze_model: false
fe_num_blocks: 8
fe_layer_norm_after_blocks: []
training_mode: forecast
samples_per_epoch: 4096
lr_max: 0.0001
lr_final_decay: 2e-6
lr_steps_warmup: 256

len_hrs: 3
step_hrs: 3

num_epochs: 32