streams_directory: "./config/streams/cams_eac4_an_era5/"
start_date: 201701010000
end_date: 202012310000
start_date_val: 202105310000
end_date_val: 202205310000

enable_chemistry_embedding: true

chemistry_reduction:
  method: "attention_based_pooling"
  target_streams: ["CAMSANALYSIS", "CAMSEAC4"]  # ✅ Specify which streams to apply ABP to
  n_species: 60
  n_levels: 1
  n_emissions: 7
  spatial_h: 451
  spatial_w: 900
  d_embedding: 1024
  d_intermediate: 256
  n_inducing: 8  # memory efficient


len_hrs: 12
step_hrs: 12

isteps: 0
lr_max: 0.00005 
forecast_steps: 3
num_epochs: 32 
freeze_modules: ".*global.*|.*local.*|.*adapter.*|.*(ERA5|CAMSANALYSIS|CAMSEAC4).*" 
fe_layer_norm_after_blocks: [3] 
impute_latent_noise_std: 0.0001



